spring.application.name=notification-service
server.port=8089

spring.datasource.url=jdbc:mysql://cine-db:3306/cine_notifications_db?createDatabaseIfNotExist=true&nullCatalogMeansCurrent=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true


spring.cloud.compatibility-verifier.enabled=false

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.api-docs.path=/api-docs