CREATE TABLE BOOKINGS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    USER_ID BIGINT NOT NULL,
    SEAT_ID BIGINT NOT NULL,
    SHOWTIME_ID BIGINT NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    CINEMA_ID BIGINT NOT NULL
);