server:
  port: 8086

spring:
  application:
    name: room-services

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    connect-retries: 10

springdoc:
  api-docs:
    enabled: true
    path: /api-docs

  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

  hateoas:
    enabled: false

  cache:
    disabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

---

spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:mysql://localhost:3306/cine_rooms_db?createDatabaseIfNotExist=true&nullCatalogMeansCurrent=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    initialization-fail-timeout: 60000
    connection-timeout: 30000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.flywaydb: DEBUG

---

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:mysql://cine-db:3306/cine_rooms_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  hikari:
    initialization-fail-timeout: 60000
    connection-timeout: 30000